name: olearistest
description: Olearis Test project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #view
  badges: ^3.1.2
  flutter_app_badger: ^1.5.0
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.5

  #logic
  auto_route: ^7.8.4
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  rxdart: ^0.27.7
  flutter_keyboard_visibility: ^5.4.1

  #rest
  dio: ^5.3.3
  http_parser: ^4.0.2

  #storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #config
  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.0
  intl: ^0.18.0
  flutter_native_splash: ^2.3.4
  fimber: ^0.7.0
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/
    - fonts/

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
